
name: Update size badge
on:
  push:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Re-knit README
        run: | 
          Rscript -e '
          install.packages("knitr")
          knitr::knit("README.Rmd")'
      
      - name: Deploy new README to Github
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          token: ${{ secrets.GH_PAT }}
          branch: main # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
          clean: false # Automatically remove deleted files from the deploy branch
